CREATE TABLE users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email VARCHAR(255) NOT NULL UNIQUE,
  username VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255),
  google_id VARCHAR(255) UNIQUE
);

CREATE TABLE profiles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL UNIQUE,
  artist_name VARCHAR(255) NOT NULL,
  pronouns VARCHAR(255),
  zone VARCHAR(255),
  bio VARCHAR(255),
  CONSTRAINT fk_profiles_user
    FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE connection_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  from_profile_id BIGINT NOT NULL,
  to_profile_id BIGINT NOT NULL,
  status VARCHAR(255) NOT NULL,
  CONSTRAINT fk_connection_requests_from_profile
    FOREIGN KEY (from_profile_id) REFERENCES profiles (id),
  CONSTRAINT fk_connection_requests_to_profile
    FOREIGN KEY (to_profile_id) REFERENCES profiles (id),
  CONSTRAINT connection_requests_status_check
    CHECK (status IN ('PENDING', 'ACCEPTED', 'REJECTED'))
);
