CREATE TABLE media_assets (
  id UUID PRIMARY KEY,
  owner_id BIGINT NOT NULL REFERENCES users(id),
  upload_key VARCHAR(500) NOT NULL UNIQUE,
  content_type VARCHAR(80) NOT NULL CHECK (content_type IN ('audio/wav','audio/mpeg','audio/flac')),
  size_bytes BIGINT NOT NULL CHECK (size_bytes > 0 AND size_bytes <= 104857600),
  sha256 VARCHAR(64) NOT NULL CHECK (sha256 ~ '^[0-9a-f]{64}$'),
  preview_seconds INTEGER CHECK (preview_seconds BETWEEN 5 AND 60),
  state VARCHAR(20) NOT NULL DEFAULT 'UPLOADING'
    CHECK (state IN ('UPLOADING','QUEUED','PROCESSING','READY','FAILED')),
  attempts INTEGER NOT NULL DEFAULT 0,
  lease_token UUID,
  lease_until TIMESTAMPTZ,
  stream_key VARCHAR(500),
  preview_key VARCHAR(500),
  duration_seconds DOUBLE PRECISION,
  failure_code VARCHAR(80),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CHECK (state <> 'READY' OR (stream_key IS NOT NULL AND duration_seconds > 0))
);
CREATE INDEX media_assets_jobs ON media_assets(state, lease_until, created_at);
CREATE INDEX media_assets_owner ON media_assets(owner_id);

CREATE TABLE releases (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_profile_id BIGINT NOT NULL REFERENCES profiles(id),
  title VARCHAR(200) NOT NULL,
  release_type VARCHAR(20) NOT NULL CHECK (release_type IN ('SINGLE','EP','ALBUM','MIX','OTHER')),
  state VARCHAR(20) NOT NULL DEFAULT 'DRAFT' CHECK (state IN ('DRAFT','PROCESSING','PUBLISHED','HIDDEN','REMOVED')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  published_at TIMESTAMPTZ
);
CREATE TABLE tracks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  release_id BIGINT NOT NULL REFERENCES releases(id),
  media_asset_id UUID REFERENCES media_assets(id),
  title VARCHAR(200) NOT NULL,
  position INTEGER NOT NULL CHECK (position > 0),
  UNIQUE (release_id, position)
);
CREATE TABLE credits (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  track_id BIGINT NOT NULL REFERENCES tracks(id),
  profile_id BIGINT REFERENCES profiles(id),
  display_name VARCHAR(200),
  role VARCHAR(80) NOT NULL,
  CHECK (profile_id IS NOT NULL OR NULLIF(TRIM(display_name), '') IS NOT NULL)
);
CREATE TABLE posts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_profile_id BIGINT NOT NULL REFERENCES profiles(id),
  body TEXT NOT NULL,
  visibility VARCHAR(20) NOT NULL DEFAULT 'PUBLIC' CHECK (visibility IN ('PUBLIC','FOLLOWERS','SUPPORTERS','TIER')),
  state VARCHAR(20) NOT NULL DEFAULT 'DRAFT' CHECK (state IN ('DRAFT','PUBLISHED','HIDDEN','REMOVED')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  published_at TIMESTAMPTZ
);
CREATE TABLE post_media (
  post_id BIGINT NOT NULL REFERENCES posts(id),
  media_asset_id UUID NOT NULL REFERENCES media_assets(id),
  PRIMARY KEY (post_id, media_asset_id)
);
CREATE INDEX releases_owner ON releases(owner_profile_id);
CREATE INDEX tracks_media ON tracks(media_asset_id);
CREATE INDEX credits_track ON credits(track_id);
CREATE INDEX posts_owner ON posts(owner_profile_id);
